name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: dependency
      run: |
        sudo apt update
        sudo apt install -y clang libelf1 libelf-dev zlib1g-dev bpftool
    - name: make
      run: make -j$(nproc)
    - name: clean
      run: make clean
